name: ci
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
    - '**/*.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Build the CLI
        run: |
          make build-cli
      - name: Build the container
        run: |
          make build-container
