name: bundle
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  bundle:
    name: release
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Set the release related variables
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          # Release tags.
          echo BUNDLE_TAG="${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        else
          echo BUNDLE_TAG="$(git describe --tags --always)" >> $GITHUB_ENV
        fi
        echo BUNDLE="quay.io/operator-framework/combo-bundle:${BUNDLE_TAG}" >> $GITHUB_ENV

    - name: Build and push bundle
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile.plainbundle
        tags: ${{ env.BUNDLE }}
        github-token: ${{ github.token }}
