name: e2e
on:
  pull_request:
    paths-ignore:
    - '**/*.md'
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2
      with:
        go-version: '~1.17'
    - name: Install kind
      run: |
        curl -sLo kind "$(curl -sL https://api.github.com/repos/kubernetes-sigs/kind/releases/latest | jq -r '[.assets[] | select(.name == "kind-linux-amd64")] | first | .browser_download_url')"
        chmod +x kind
        sudo mv kind /bin/
    - name: Create kind cluster
      run: |
        kind create cluster
        kind export kubeconfig
    - name: Run e2e tests
      run: make run-e2e
