name: ci
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
    - '**/*.md'
jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      # - name: Check out repository code
      #   uses: actions/checkout@v2
      - name: Identify action URL
        run : |
          echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      # - name: Install Go 1.17
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: '1.17'
      # - name: Vendor dependencies
      #   run: go mod vendor
      # - name: Run sanity checks
      #   run: make verify
