name: unit
on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run unit tests
        run: |
          make test-unit
